name = "SymbolicsMathLink"
uuid = "7963cd39-1b62-4514-9cf0-788fb5452611"
authors = ["E. Swagel"]
version = "2.0.1"

[deps]
MathLink = "18c93696-a329-5786-9845-8443133fa0b4"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[compat]
julia = "1"
MathLink = ">=0.5.1"
SpecialFunctions = ">=2.3.0"
Symbolics = ">=4.10.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
